version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing CDK...
      - npm -g install aws-cdk
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Deploying Change...
      - cdk deploy
